SELECT ins.NAME, ins.DATETIME 
FROM ANIMAL_INS AS ins
LEFT OUTER JOIN ANIMAL_OUTS AS outs
ON ins.ANIMAL_ID = outs.ANIMAL_ID
WHERE outs.NAME IS NULL AND ins.NAME IS NOT NULL
ORDER BY ins.DATETIME LIMIT 3;
