SELECT fo.PRODUCT_ID, fp.PRODUCT_NAME, fp.PRICE * SUM(fo.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER fo 
JOIN FOOD_PRODUCT fp
ON fo.PRODUCT_ID = fp.PRODUCT_ID AND YEAR(fo.PRODUCE_DATE) = 2022 AND MONTH(fo.PRODUCE_DATE) = 5
GROUP BY fo.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, fo.PRODUCT_ID ASC;